server:
  port: '9005'
spring:
  data:
    mongodb:
      database: bank
      port: '27017'
      host: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
